=== not-things-modular/not-things-vcv/res/timeseq.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://not-things.com/timeseq/0.0.1",
	"definitions": {
		"id-base": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"minLength": 1
				}
			},
			"required": [ "id" ]
		},
		"ref-base": {
			"type": "object",
			"title": "by ref",
			"properties": {
				"ref": {
					"type": "string",
					"minLength": 1
				}
			},
			"required": [ "ref" ]
		},
		"input": {
			"type": "object",
			"title": "input",
			"properties": {
				"index": {
					"type": "integer",
					"minimum": 0,
					"maximum": 8
				},
				"channel": {
					"type": "integer",
					"minimum": 0,
					"maximum": 8
				}
			},
			"required": [ "index" ]
		},
		"output": {
			"type": "object",
			"title": "output",
			"properties": {
				"index": {
					"type": "integer",
					"minimum": 0,
					"maximum": 8
				},
				"channel": {
					"type": "integer",
					"minimum": 0,
					"maximum": 8
				}
			},
			"required": [ "index" ]
		},
		"rand": {
			"type": "object",
			"title": "rand",
			"properties": {
				"lower": {
					"oneOf": [
						{ "$ref": "#/definitions/ref-base" },
						{ "$ref": "#/definitions/value" }
					]
				},
				"upper": {
					"oneOf": [
						{ "$ref": "#/definitions/ref-base" },
						{ "$ref": "#/definitions/value" }
					]
				}
			},
			"required": [ "lower", "upper" ]
		},
		"calc": {
			"type": "array",
			"title": "calc",
			"items": {
				"type": "object",
				"oneOf": [
					{
						"title": "add",
						"properties": {
							"add": {
								"oneOf": [
									{ "$ref": "#/definitions/ref-base" },
									{ "$ref": "#/definitions/value" }
								]
							}
						},
						"required": [ "add" ]
					},
					{
						"title": "sub",
						"properties": {
							"sub": {
								"oneOf": [
									{ "$ref": "#/definitions/ref-base" },
									{ "$ref": "#/definitions/value" }
								]
							}
						},
						"required": [ "sub" ]
					},
					{
						"title": "div",
						"properties": {
							"div": {
								"oneOf": [
									{ "$ref": "#/definitions/ref-base" },
									{ "$ref": "#/definitions/value" }
								]
							}
						},
						"required": [ "div" ]
					},
					{
						"title": "mult",
						"properties": {
							"mult": {
								"oneOf": [
									{ "$ref": "#/definitions/ref-base" },
									{ "$ref": "#/definitions/value" }
								]
							}
						},
						"required": [ "mult" ]
					}
				]
			},
			"minItems": 1
		},
		"value": {
			"type": "object",
			"title": "value",
			"oneOf": [
				{
					"title": "voltage",
					"properties": {
						"voltage": {
							"type": "number",
							"minimum": -10,
							"maximum": 10
						}
					},
					"required": [ "voltage" ]
				},
				{
					"title": "note",
					"properties": {
						"note": {
							"type": "string",
							"minLength": 2,
							"maxLength": 3,
							"pattern": "[a-zA-Z][0-9][+-]?"
						}
					},
					"required": [ "note" ]
				},
				{
					"title": "variable",
					"properties": {
						"variable": {
							"type": "string",
							"minLength": 1
						}
					},
					"required": [ "variable" ]
				},
				{
					"title": "input",
					"properties": {
						"input": {
							"oneOf": [
								{ "$ref": "#/definitions/ref-base" },
								{ "$ref": "#/definitions/input" }
							]
						}
					},
					"required": [ "input" ]
				},
				{
					"title": "output",
					"properties": {
						"output": {
							"oneOf": [
								{ "$ref": "#/definitions/ref-base" },
								{ "$ref": "#/definitions/output" }
							]
						}
					},
					"required": [ "output" ]
				},
				{
					"title": "rand",
					"properties": {
						"rand": { "$ref": "#/definitions/rand" }
					},
					"required": [ "rand" ]
				},
				{
					"title": "calc",
					"properties": {
						"calc": {
							"oneOf": [
								{ "$ref": "#/definitions/ref-base" },
								{ "$ref": "#/definitions/calc" }
							]
						}
					},
					"required": [ "calc" ]
				}
			]
		},
		"set-value": {
			"type": "object",
			"title": "set-value",
			"ui:label": "false",
			"properties": {
				"output": {
					"oneOf": [
						{ "$ref": "#/definitions/ref-base" },
						{ "$ref": "#/definitions/output" }
					]
				},
				"value": {
					"oneOf": [
						{ "$ref": "#/definitions/ref-base" },
						{ "$ref": "#/definitions/value" }
					]
				}
			},
			"required": [ "output", "value" ]
		},
		"set-variable": {
			"type": "object",
			"title": "set-variable",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"value": {
					"oneOf": [
						{ "$ref": "#/definitions/ref-base" },
						{ "$ref": "#/definitions/value" }
					]
				}
			},
			"required:": [ "name", "value" ]
		},
		"set-polyphony": {
			"type": "object",
			"title": "set-polyphony",
			"properties": {
				"index": {
					"type": "integer",
					"minimum": 0,
					"maximum": 8
				},
				"channels": {
					"type": "integer",
					"minimum": 1,
					"maximum": 16
				}
			},
			"required": [ "index", "channels" ]
		},
		"action": {
			"type": "object",
			"title": "action",
			"properties": {
				"timing": {
					"enum": [ "start", "end", "glide" ]
				}
			},
			"if": {
				"properties": { "timing": { "const": "glide" } }
			},
			"then": {
				"properties": {
					"start-value": {
						"oneOf": [
							{ "$ref": "#/definitions/ref-base" },
							{ "$ref": "#/definitions/value" }
						]
					},
					"end-value": {
						"oneOf": [
							{ "$ref": "#/definitions/ref-base" },
							{ "$ref": "#/definitions/value" }
						]
					}
				},
				"oneOf": [
					{
						"title": "output",
						"properties": {
							"output": {
								"oneOf": [
									{ "$ref": "#/definitions/ref-base" },
									{ "$ref": "#/definitions/output" }
								]
							}
						},
						"required": [ "output" ]
					},
					{
						"title": "variable",
						"properties": {
							"variable": {
								"type": "string"
							}
						},
						"required": [ "variable" ]
					}
				],
				"required": [ "start-value", "end-value" ]
			},
			"else": {
				"oneOf": [
					{
						"title": "set-value",
						"properties": {
							"set-value": { "$ref": "#/definitions/set-value" }
						},
						"required": [ "set-value" ]
					},
					{
						"title": "set-variable",
						"properties": {
							"set-variable": { "$ref": "#/definitions/set-variable" }
						},
						"required": [ "set-variable" ]
					},
					{
						"title": "set-polyphony",
						"properties": {
							"set-polyphony": { "$ref": "#/definitions/set-polyphony" }
						},
						"required": [ "set-polyphony" ]
					},
					{
						"title": "trigger",
						"properties": {
							"trigger": {
								"type": "string",
								"minLenght": 1
							}
						},
						"required": [ "trigger" ]
					}
				]
			}
		},
		"duration": {
			"type": "object",
			"title": "duration",
			"oneOf": [
				{
					"title": "samples",
					"properties": {
						"samples": {
							"type": "integer",
							"exclusiveMinimum": 0
						}
					},
					"required": [ "samples" ]
				},
				{
					"title": "millis",
					"properties": {
						"millis": {
							"type": "number",
							"exclusiveMinimum": 0
						}
					},
					"required": [ "millis" ]
				},
				{
					"title": "beats",
					"properties": {
						"bars": {
							"type": "integer",
							"exclusiveMinimum": 0
						},
						"beats": {
							"type": "number",
							"exclusiveMinimum": 0
						}
					},
					"required": [ "beats" ]
				}
			]
		},
		"segment": {
			"type": "object",
			"title": "segment",
			"properties": {
				"duration": { "$ref": "#/definitions/duration" },
				"actions": {
					"type": "array",
					"items": {
						"oneOf": [
							{ "$ref": "#/definitions/ref-base" },
							{ "$ref": "#/definitions/action" }
						]
					},
					"minItems": 1
				}
			},
			"required": [ "duration" ]
		},
		"segment-block": {
			"type": "object",
			"title": "segment-block",
			"properties": {
				"segments": {
					"type": "array",
					"items": {
						"type": "object",
						"oneOf": [
							{
								"title": "segment",
								"properties": {
									"segment": {
										"oneOf": [
											{ "$ref": "#/definitions/ref-base" },
											{ "$ref": "#/definitions/segment" }
										]
									}
								},
								"required": [ "segment" ]
							},
							{
								"title": "segment-block",
								"properties": {
									"segment-block": {
										"oneOf": [
											{ "$ref": "#/definitions/ref-base" },
											{ "$ref": "#/definitions/segment-block" }
										]
									}
								},
								"required": [ "segment-block" ]
							}
						]
					}
				}
			},
			"required": [ "segments" ]
		},
		"lane": {
			"type": "object",
			"title": "lane",
			"properties": {
				"auto-start": {
					"type": "boolean"
				},
				"loop": {
					"type": "boolean"
				},
				"repeat": {
					"type": "integer",
					"minimum": 1
				},
				"start-trigger": {
					"type": "string",
					"minLength": 1
				},
				"stop-trigger": {
					"type": "string",
					"minLength": 1
				},
				"segments": {
					"type": "array",
					"items": {
						"type": "object",
						"oneOf": [
							{
								"title": "segment",
								"properties": {
									"segment": {
										"oneOf": [
											{ "$ref": "#/definitions/ref-base" },
											{ "$ref": "#/definitions/segment" }
										]
									}
								},
								"required": [ "segment" ]
							},
							{
								"title": "segment-block",
								"properties": {
									"segment-block": {
										"oneOf": [
											{ "$ref": "#/definitions/ref-base" },
											{ "$ref": "#/definitions/segment-block" }
										]
									}
								},
								"required": [ "segment-block" ]
							}
						]
					}
				}
			},
			"required": [ "segments" ]
		},
		"time-scale": {
			"type": "object",
			"title": "time-scale",
			"properties": {
				"sample-rate": {
					"type": "integer",
					"title": "Reference sample rate",
					"minimum": 1
				},
				"bpm": {
					"type": "integer",
					"title": "Beats per minute",
					"minimum": 1
				},
				"bpp": {
					"type": "integer",
					"title": "Beats per bar",
					"minimum": 1
				}
			}
		},
		"timeline": {
			"type": "object",
			"title": "timeline",
			"properties": {
				"time-scale": { "$ref": "#/definitions/time-scale" },
				"loop-lock": {
					"type": "boolean",
					"title": "Lock lanes for looping"
				},
				"lanes": {
					"type": "array",
					"title": "Timelanes",
					"items": {
						"$ref": "#/definitions/lane"
					},
					"minItems": 1
				}
			},
			"required": [ "lanes" ]
		},
		"input-trigger": {
			"type": "object",
			"title": "input-trigger",
			"properties": {
				"id": {
					"type": "string",
					"minLength": 1
				},
				"input": {
					"oneOf": [
						{ "$ref": "#/definitions/ref-base" },
						{ "$ref": "#/definitions/input" }
					]
				}
			},
			"required": [ "id", "input" ]
		},
		"script": {
			"type": "object",
			"title": "script",
			"properties": {
				"type": {
					"const": "not-things_timeseq_script"
				},
				"version": {
					"const": "0.0.1"
				},
				"global-actions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/action"
					}
				},
				"timelines": {
					"type": "array",
					"title": "Timelines",
					"items": {
						"$ref": "#/definitions/timeline"
					},
					"minItems": 1
				},
				"segment-blocks": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/segment-block" }
						]
					},
					"minItems": 1
				},
				"segments": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/segment" }
						]
					},
					"minItems": 1
				},
				"inputs": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/input" }
						]
					},
					"minItems": 1
				},
				"outputs": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/output" }
						]
					},
					"minItems": 1
				},
				"calcs": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/calc" }
						]
					},
					"minItems": 1
				},
				"values": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/value" }
						]
					},
					"minItems": 1
				},
				"actions": {
					"type": "array",
					"items": {
						"allOf": [
							{ "$ref": "#/definitions/id-base" },
							{ "$ref": "#/definitions/action" }
						]
					},
					"minItems": 1
				},
				"input-triggers": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/input-trigger"
					},
					"minItems": 1
				}
			},
			"required": [ "type", "version", "timelines" ]
		}
	},
	"$ref": "#/definitions/script"
}

=== not-things-modular/not-things-vcv/test/resources/timeseq/bernoulli-basic.json
{
	"type": "not-things_timeseq_script",
	"version": "0.0.1",
	"timelines": [
		{
			"lanes": [
				{
					"auto-start": false,
					"loop": false,
					"start-trigger": "determine-output",
					"segments": [
						{
							"duration": { "millis": 500 },
							"actions": [
								{
									"timing": "start",
									"set-variable": {
										"name": "bernoulli-chance",
										"value": {
											"rand": {
												"lower": { "voltage": 0 },
												"upper": { "voltage": 10 }
											}
										}
									}
								},
								{
									"timing": "start",
									"set-value": {
										"output": { "index": 3 },
										"value": { "variable": "bernoulli-chance" }
									}
								},
								{
									"timing": "start",
									"if": {
										"gt": [
											{ "variable": "bernoulli-chance" },
											{ "voltage": 5 }
										]
									},
									"set-value": {
										"output": { "index": 1 },
										"value": { "voltage": 10 }
									}
								},
								{
									"timing": "start",
									"if": {
										"lte": [
											{ "variable": "bernoulli-chance" },
											{ "voltage": 5 }
										]
									},
									"set-value": {
										"output": { "index": 2 },
										"value": { "voltage": 10 }
									}
								}
							]
						},
						{
							"duration": { "samples": 1 },
							"actions": [
								{
									"timing": "start",
									"set-value": {
										"output": { "index": 1 },
										"value": { "voltage": 0 }
									}
								},
								{
									"timing": "start",
									"set-value": {
										"output": { "index": 2 },
										"value": { "voltage": 0 }
									}
								}
							]
						}
					]
				}
			]
		}
	],
	"input-triggers": [
		{
			"id": "determine-output",
			"input": { "index": 1 }
		}
	]
}

=== not-things-modular/not-things-vcv/test/resources/timeseq/rand-3.json
{
	"type": "not-things_timeseq_script",
	"version": "0.0.1",
	"timelines": [
		{
			"lanes": [
				{
					"auto-start": false,
					"loop": false,
					"start-trigger": "determine-output",
					"segments": [
						{
							"duration": { "millis": 1 },
							"actions": [
								{
									"set-value": {
										"output": { "index": 1 },
										"value": { "voltage": 0 }
									}
								},
								{
									"set-value": {
										"output": { "index": 2 },
										"value": { "voltage": 0 }
									}
								},
								{
									"set-value": {
										"output": { "index": 3 },
										"value": { "voltage": 0 }
									}
								},
								{
									"set-variable": {
										"name": "do-output",
										"value": {
											"rand": {
												"lower": { "voltage": 0 },
												"upper": { "voltage": 10 }
											}
										}
									}
								},
								{
									"set-value": {
										"output": { "index": 4 },
										"value": { "variable": "do-output" }
									}
								},
								{
									"if": {
										"gt": [
											{ "variable": "do-output" },
											{ "voltage": 7.5 }
										]
									},
									"set-variable": {
										"name": "output-select",
										"value": {
											"rand": {
												"lower": { "voltage": 0 },
												"upper": { "voltage": 3 }
											}
										}
									}
								},
								{
									"set-value": {
										"output": { "index": 5 },
										"value": { "variable": "output-select" }
									}
								},
								{
									"if": {
										"and": [
											{
												"gt": [
													{ "variable": "do-output" },
													{ "voltage": 7.5 }
												]
											},
											{
												"lt": [
													{ "variable": "output-select" },
													{ "voltage": 1 }
												]
											}
										]
									},
									"set-value": {
										"output": { "index": 1 },
										"value": { "voltage": 10 }
									}
								},
								{
									"if": {
										"and": [
											{
												"and": [
													{
														"gt": [
															{ "variable": "do-output" },
															{ "voltage": 7.5 }
														]
													},
													{
														"gte": [
															{ "variable": "output-select" },
															{ "voltage": 1 }
														]
													}
												]
											},
											{
												"lt": [
													{ "variable": "output-select" },
													{ "voltage": 2 }
												]
											}
										]
									},
									"set-value": {
										"output": { "index": 2 },
										"value": { "voltage": 10 }
									}
								},
								{
									"if": {
										"and": [
											{
												"and": [
													{
														"gt": [
															{ "variable": "do-output" },
															{ "voltage": 7.5 }
														]
													},
													{
														"gte": [
															{ "variable": "output-select" },
															{ "voltage": 2 }
														]
													}
												]
											},
											{
												"lt": [
													{ "variable": "output-select" },
													{ "voltage": 3 }
												]
											}
										]
									},
									"set-value": {
										"output": { "index": 3 },
										"value": { "voltage": 10 }
									}
								}
							]
						}
					]
				}
			]
		}
	],
	"input-triggers": [
		{
			"id": "determine-output",
			"input": { "index": 1 }
		}
	]
}

=== not-things-modular/not-things-vcv/test/resources/timeseq/bernoulli-full.json
{
	"type": "not-things_timeseq_script",
	"version": "0.0.1",
	"timelines": [
		{
			"lanes": [
				{
					"auto-start": false,
					"loop": false,
					"start-trigger": "determine-output",
					"segments": [
						{
							"duration": { "millis": 1 },
							"actions": [
								{
									"timing": "start",
									"set-variable": {
										"name": "bernoulli-chance",
										"value": {
											"rand": {
												"lower": { "voltage": 0 },
												"upper": { "voltage": 10 }
											}
										}
									}
								},
								{
									"timing": "start",
									"set-value": {
										"output": { "index": 3 },
										"value": { "variable": "bernoulli-chance" }
									}
								},
								{
									"timing": "start",
									"if": {
										"gt": [
											{ "variable": "bernoulli-chance" },
											{ "input": { "index": 2 } }
										]
									},
									"set-value": {
										"output": { "index": 1 },
										"value": { "voltage": 10 }
									}
								},
								{
									"timing": "start",
									"if": {
										"lte": [
											{ "variable": "bernoulli-chance" },
											{ "input": { "index": 2 } }
										]
									},
									"set-value": {
										"output": { "index": 2 },
										"value": { "voltage": 10 }
									}
								},
								{
									"timing": "start",
									"trigger": "reset-output"
								}
							]
						}
					]
				},
				{
					"auto-start": false,
					"loop": true,
					"start-trigger": "reset-output",
					"stop-trigger": "stop-reset-output",
					"segments": [
						{
							"duration": { "samples": 1 },
							"actions": [
								{
									"timing": "start",
									"if": {
										"lt": [
											{ "input": { "index": 1 } },
											{ "voltage": 1 }
										]
									},
									"set-value": {
										"output": { "index": 1 },
										"value": { "voltage": 0 }
									}
								},
								{
									"timing": "start",
									"if": {
										"lt": [
											{ "input": { "index": 1 } },
											{ "voltage": 1 }
										]
									},
									"set-value": {
										"output": { "index": 2 },
										"value": { "voltage": 0 }
									}
								},
								{
									"timing": "start",
									"if": {
										"lt": [
											{ "input": { "index": 1 } },
											{ "voltage": 1 }
										]
									},
									"trigger": "stop-reset-output"
								}
							]
						}
					]
				}
			]
		}
	],
	"input-triggers": [
		{
			"id": "determine-output",
			"input": { "index": 1 }
		}
	]
}

=== not-things-modular/not-things-vcv/test/resources/simple-sequencer.json
{
	"type": "not-things_timeseq_script",
	"version": "0.0.1",
	"global-actions": [
		{
			"timing": "start",
			"set-polyphony": {
				"index": 1,
				"channels": 2
			}
		},
		{
			"timing": "start",
			"set-polyphony": {
				"index": 2,
				"channels": 2
			}
		},
		{
			"timing": "start",
			"set-value": {
				"output": {
					"index": 1
				},
				"value": {
					"voltage": 1.01
				}
			}
		},
		{
			"timing": "start",
			"set-value": {
				"output": {
					"index": 2
				},
				"value": {
					"note": "E3+"
				}
			}
		},
		{
			"timing": "end",
			"set-value": {
				"output": {
					"index": 1
				},
				"value": {
					"voltage": -1.01
				}
			}
		},
		{
			"timing": "start",
			"set-value": {
				"output": {
					"index": 2
				},
				"value": {
					"note": "F5-"
				}
			}
		}
	],
	"timelines": [
		{
			"lanes": [
				{
					"auto-start": true,
					"loop": true,
					"segments": [
						{
							"segment": {
								"duration": {
									"samples": 183
								},
								"actions": [
									{
										"timing": "glide",
										"start-value": {
											"voltage": -5.0
										},
										"end-value": {
											"voltage": 5.0
										},
										"output": {
											"index": 7
										}
									}
								]
							}
						}
					]
				}
			]
		}
	]}
